version: "3.3"
services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PSW}
      - MYSQL_ROOT_PASSWORD=${ROOT_PSW}
    volumes:
      - "./db/init.sql:/docker-entrypoint-initdb.d/init.sql"
    networks:
      - network
  back:
    image: back_image
    ports:
      - "3000:3000"
    networks:
      - network
    environment:
      - MYSQL_HOST=db
      - GIPHY=${GIPHY}
  front:
    image: front_image
    ports:
      - "8080:8080"
    environment:
      - BASE_URL=${BASE_URL}

networks:
  network:
